final List<String> breeds = [
    "Affenpinscher",
    "Airedale",
    "Akita",
    "Appenzeller",
    "Aasenji",
    "Beagle",
    "Bluetick",
    "Borzoi",
    "Bouvier",
    "Boxer",
    "Brabancon",
    "Briard",
    "Boston Bulldog",
    "Boston Bulldog",
    "English Bulldog",
    "French Bulldog",
    "Staffordshire Bullterrier",
    "Cairn",
    "Australian Cattledog",
    "Chihuahua",
    "Chow",
    "Clumber",
    "Cockapoo",
    "Border Collie",
    "Coonhound",
    "Corgi",
    "Cotondetulear",
    "Dachshund",
    "Dalmatian",
    "Great Dane",
    "Deerhound",
    "Dingo",
    "Doberman",
    "Elkhound",
    "Entlebucher",
    "Eskimo",
    "Bichon Frise",
    "German Shepherd",
    "Greyhound",
    "Groenendael",
    "Afghan Hound",
    "Basset Hound",
    "Blood Hound",
    "English Hound",
    "Ibizan Hound",
    "Walker Hound",
    "Husky",
    "Keeshond",
    "Kelpie",
    "Komondor",
    "Kuvasz",
    "Labrador",
    "Leonberg",
    "Lhasa",
    "Malamute",
    "Malinois",
    "Maltese",
    "Bull Mastiff",
    "English Mastiff",
    "Tibetan Mastiff",
    "Mix",
    "Bernese Mountain",
    "Swiss Mountain",
    "Newfoundland",
    "Otterhound",
    "Papillon",
    "Pekinese",
    "Pembroke",
    "Pinscher",
    "Pointer",
    "Pomeranian",
    "Miniature Poodle",
    "Standard Poodle",
    "Toy Poodle",
    "Pug",
    "Puggle",
    "Pyrenees",
    "Redbone",
    "Chesapeake Retriever",
    "Curly Retriever",
    "Flatcoated Retriever",
    "Golden Retriever",
    "Ridgeback",
    "Rottweiler",
    "Saluki",
    "Samoyed",
    "Schipperke",
    "Schnauzer",
    "English Setter",
    "Gordon Setter",
    "Irish Setter",
    "English Sheepdog",
    "Shetland Sheepdog",
    "Shiba",
    "Shih-Tzu",
    "Blenheim Spaniel",
    "Brittany Spaniel",
    "Cocker Spaniel",
    "Irish Spaniel",
    "Japanese Spaniel",
    "Sussex Spaniel",
    "Welsh Spaniel",
    "English Springer",
    "St. Bernard",
    "American Terrier",
    "Australian Terrier",
    "Bedlington Terrier",
    "Border Terrier",
    "Dandie Terrier",
    "Fox Terrier",
    "Irish Terrier",
    "Kerryblue Terrier",
    "Lakeland Terrier",
    "Norfolk Terrier",
    "Norwich Terrier",
    "Patterdale Terrier",
    "Russell Terrier",
    "Scottish Terrier",
    "Sealyham Terrier",
    "Silky Terrier",
    "Tibetan Terrier",
    "Toy Terrier",
    "Westhighland Terrier",
    "Wheaten Terrier",
    "Yorkshire Terrier",
    "Vizsla",
    "Weimaraner",
    "Whippet",
    "Irish Wolfhound",
  ];

